#!/bin/bash

# Get the user's configured name from git
user_name=$(git config user.name)

# Define dev_id mapping for contributors
case "$user_name" in
"cicciord")
	dev_id="(s323518) "
	;;
"leoriz1")
	dev_id="(s328764) "
	;;
"fred")
	dev_id="(s322787) "
	;;
"s328743_poli")
	dev_id="(s328743) "
	;;
*)
	dev_id=""
	;;
esac

# Check if dev_id is already present in the commit message
if ! grep -q "$dev_id" "$1"; then
	# Prepend dev_id to the commit message
	sed -i.bak -e "1s/^/$dev_id/" "$1"
fi
